Wcy
zixiangcode/TinyTikTok pull request #10
Opened 2023-08-22 03:12 UTC by wcynb1023

添加功能 关注操作，关注列表，粉丝列表，朋友列表

2023-08-23 11:35 UTC, surkaa approved these changes
well

2023-08-24 05:02 UTC, zixiangcode requested changes
整体结构上可以分开写，有 `Service` 层的 `RelationService` 和 `impl` 层的 `RelationServiceImpl`。可以参考 `UserService.go` 来修改。

2023-08-24 05:02 UTC, zixiangcode commented on models/User.go
> +	Token           string `json:"token,omitempty"`
为什么在这里要加上 `Token` 属性？

2023-08-24 05:02 UTC, zixiangcode commented on service/impl/UserServiceImpl.go
> +	token := username + password
`token` 在生成和解析时均采用 `JWT` 中的方法，为什么仍然采用 `username` + `pwd` 的方式？这里的 `token` 作用是什么？

2023-08-24 05:02 UTC, zixiangcode commented on dao/User.go
> +func FindUserById(id int64) (*models.User, error) {
在 `UserServiceImpl.go` 中已经实现过了

2023-08-24 05:02 UTC, zixiangcode commented on dao/User.go
> +func FindUserByToken(token string) (*models.User, error) {
`token` 不应该是一个 `User` 对象的属性值，不应该存在这个函数。

2023-08-24 05:02 UTC, zixiangcode commented on dao/User.go
删除此文件

2023-08-24 05:02 UTC, zixiangcode commented on dao/relation.go
> +func AddFollow(owner *models.User, Target *models.User) error {
应该确保自己不能关注/取关自己

2023-08-24 05:02 UTC, zixiangcode commented on models/Relation.go
> +type Relation struct {
建议将 `Relation` 改为 `Follow` ，语义更清晰。另外，`CreateTime` 是必要的属性吗？
考虑下面的写法（仅供参考）：
```go
type Follow struct {
	utils.CommonEntity
	UserId       int64 `json:"UserId"`
	FollowUserId int64 `json:"FollowUserId"`
}
```

2023-08-26 02:48 UTC, closed without merging