Dev peiyong
zixiangcode/TinyTikTok pull request #11
Opened 2023-08-23 06:24 UTC by HelloAmireux

完成视频上传接口

2023-08-23 10:33 UTC, winingYang reviewed
good

2023-08-23 11:36 UTC, winingYang approved these changes
OK

2023-08-24 15:56 UTC, zixiangcode requested changes

2023-08-24 15:56 UTC, zixiangcode commented on image/d60bef69-63a2-4d36-b77b-6d56f06dfb72
二进制文件可以删除

2023-08-24 15:56 UTC, zixiangcode commented on config/config.go
> +
`config.go` 存放的不是具体的配置，是存放配置的结构体和如何解析配置。具体的配置变量是存在 `configuration.json` 中的。然后在 `Configuration` 这个结构体中添加。譬如：
```go
type Configuration struct {
	Mysql string `json:"Mysql"`
	AccessKeyId string `json:"AccessKeyId"`
}
```

2023-08-24 15:56 UTC, zixiangcode commented on controller/publish.go
> +	fmt.Println("videoService.Publish(data, userId) 成功")
这种开发过程中辅助自己测试的语句可以去除掉。也尽量使用状态码+状态信息的方式打印日志。

2023-08-24 15:56 UTC, zixiangcode commented on image/d60bef69-63a2-4d36-b77b-6d56f06dfb72.jpg
视频文件什么的可以放在原有的 `public` 文件夹或其子目录，目录结构更清晰

2023-08-24 15:56 UTC, zixiangcode commented on db/MySql.go
> +	dsn := "root:123456@tcp(127.0.0.1:3306)/TinyTikTok?charset=utf8mb4&parseTime=True"
这里可以参考 `db, err := gorm.Open(mysql.Open(config.Config.Mysql), &gorm.Config{})`，这样直接写不适合后期修改，写 `config` 的目的就是为了避免在其他文件中出现具体的配置数据。

2023-08-24 15:56 UTC, zixiangcode commented on controller/publish.go
> +func createVideoServiceImpl() impl.VideoServiceImpl { //创建一个视频流接口
方法名改为 `GetVideoService` 更合适点

2023-08-24 15:56 UTC, zixiangcode commented on controller/publish.go
> +		fmt.Println("转化出问题了")
这种直接打印日志是不合规范的，应该返回 `json` 数据 `c.JSON(...)` ，这种。

2023-08-24 15:56 UTC, zixiangcode commented on service/VideoService.go
> +	IsExist(userId int64)(bool,error)//查询用户是否存在
这个方法有必要吗？而且应该存在于 `VideoService` 中吗？

2023-08-24 15:56 UTC, zixiangcode commented on service/impl/videoServiceImpl.go
> +const FilePath = "http://localhost:8080/"
这种配置信息不应该放在这里，考虑放在 `config` 层

2023-08-24 15:56 UTC, zixiangcode commented on models/Video.go
> +	Author        User   `json:"author" gorm:"foreignKey:UserID" json:"user"`                             // 视频作者信息
这里 `gorm` 的外键应该写错了，尝试改为 `gorm:"foreignKey:userID` ，也就是 `foreignKey` 后参考的名称应该是结构体中的属性名，大小写有误。

2023-08-24 15:56 UTC, zixiangcode commented on models/Video.go
> +	userID 		int64	`json:"user_id" gorm:"column:user_id"`
这里是否存在冗余呢？因为在 `Author` 属性和 `CommonEntity` 属性中都已经存在了用户的 ID 信息，请斟酌

2023-08-24 15:56 UTC, zixiangcode commented on service/impl/videoServiceImpl.go
> +	// 创建OSS客户端
建议先将代码中所有与云服务器相关内容去除，便于开发过程中的 debug，待到后期完成整个项目后再考虑优化上云服务器的内容

2023-08-24 15:56 UTC, zixiangcode commented on service/impl/videoServiceImpl.go
> +	videoName := uuid.V4()
不是传入了 `title` 参数吗？这又生成一个 `videoName` 是何意？

2023-08-24 15:56 UTC, zixiangcode commented on service/impl/videoServiceImpl.go
> +	err = InsertVideo(videoName,userId,title)
云服务器内容去除，删除 `InsertVideo` 方法，将保存到数据库的内容写到 `SaveVideo` 中。同时，`SaveVideo` 应该只进行保存到数据库的操作，对视频文件的处理等操作应该在 `Publish` 方法中。
另外，用户执行完 `Publish` 操作，应该使其发布作品数目+1

2023-08-24 15:56 UTC, zixiangcode commented on service/impl/videoServiceImpl.go
> +	//if result.Error!=nil{
`result` 本身就是 `.Error`，这里重复调用了

2023-09-05 12:57 UTC, Kiro-Young approved these changes

2023-09-06 07:05 UTC, closed without merging